name: Deploy System API

on:
  push:
    branches:
      - DEV
      - PRE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Determine environment based on branch
        id: envselect
        run: |
          if [[ "${GITHUB_REF##*/}" == "DEV" ]]; then
            echo "PROFILE=dev" >> $GITHUB_OUTPUT
            echo "ENV=dev" >> $GITHUB_OUTPUT
          else
            echo "PROFILE=pre" >> $GITHUB_OUTPUT
            echo "ENV=pre" >> $GITHUB_OUTPUT
          fi

      - name: Build and Publish to Exchange
        run: |
          mvn -s .mvn/settings.xml \
              -P${{ steps.envselect.outputs.PROFILE }} \
              -Denv=${{ steps.envselect.outputs.ENV }} \
              clean deploy

      - name: Deploy to CloudHub 2.0
        run: |
          mvn -s .mvn/settings.xml \
              -P${{ steps.envselect.outputs.PROFILE }} \
              -Denv=${{ steps.envselect.outputs.ENV }} \
              -DmuleDeploy \
              package